#!/usr/bin/env bash
# dream-report.sh — compose the dated nightly report from the night's job records.
#
# C4 in the brief. Composed from three pieces of proven prior art rather than
# invented: `dispatch-gate-report.sh` (the zero-LLM, cron-safe generator shape),
# `night-shift.md:414-433` (Completed / needs-review / telemetry sectioning), and
# `maintenance.md:172` (dual-location write, so it lands somewhere actually seen).
#
# KD-6 — THE REPORT IS WRITTEN UNCONDITIONALLY, AND ITS ABSENCE IS THE ALARM.
# Routine status reports infrastructure success, not task success, and there are
# no failure notifications. So a clean night and a night that never ran must not
# look alike: every job appears in the § Every job checked table with its result,
# even when the result is "nothing found". A report with zero job records is
# itself reported as a malfunction rather than rendered as a quiet success.
#
# NO LLM, NO NETWORK, NO JUDGMENT. Every line here is a transformation of a
# record it was handed. Narrative generated over the top of correct numbers is a
# live failure mode, not a theoretical one: on 2026-07-24 the spike routine's own
# prose called a 614k-second gap "~118k seconds" while reporting the raw epochs
# correctly. This script never writes a sentence the caller did not supply.
#
# Input: job records on stdin, one per line, tab-separated:
#   <job-slug>\t<status>\t<summary>\t<detail>\t<link>
#   status = did | skipped | flagged | clean
#   detail and link may be empty.
#
# Usage:
#   dream-report.sh --out=<path> [--also=<path>] [--ran-at=<text>]
#                   [--repo=<name>=<sha>]... [--mode=dry-run|armed] < records.tsv
set -euo pipefail

OUT=""
ALSO=""
RAN_AT=""
MODE="dry-run"
REPOS=""

for arg in "$@"; do
  case "$arg" in
    --out=*)    OUT="${arg#*=}" ;;
    --also=*)   ALSO="${arg#*=}" ;;
    --ran-at=*) RAN_AT="${arg#*=}" ;;
    --mode=*)   MODE="${arg#*=}" ;;
    --repo=*)   if [ -z "$REPOS" ]; then REPOS="${arg#*=}"; else REPOS="$REPOS
${arg#*=}"; fi ;;
    *) echo "dream-report.sh: unknown argument: $arg" >&2; exit 2 ;;
  esac
done

[ -n "$OUT" ] || { echo "dream-report.sh: --out is required" >&2; exit 2; }
case "$MODE" in
  dry-run|armed) ;;
  *) echo "dream-report.sh: --mode must be dry-run or armed" >&2; exit 2 ;;
esac
[ -n "$RAN_AT" ] || RAN_AT=$(date -u '+%Y-%m-%d %H:%M UTC')

RECORDS=$(mktemp)
trap 'rm -f "$RECORDS"' EXIT
cat > "$RECORDS"

# Counted on non-blank lines only: a trailing newline in the record stream would
# otherwise render as an empty table row, which reads like a job that failed to
# report rather than an artifact of the pipe.
n_total=$(grep -c '[^[:space:]]' "$RECORDS" || true)
n_did=$(awk -F'\t' '$2=="did"' "$RECORDS" | grep -c '[^[:space:]]' || true)
n_skipped=$(awk -F'\t' '$2=="skipped"' "$RECORDS" | grep -c '[^[:space:]]' || true)
n_flagged=$(awk -F'\t' '$2=="flagged"' "$RECORDS" | grep -c '[^[:space:]]' || true)
n_clean=$(awk -F'\t' '$2=="clean"' "$RECORDS" | grep -c '[^[:space:]]' || true)

# "Needs you" is the only number in the report USER has to act on, so it is
# the only one in the header. Flagged and skipped both need a human; did and
# clean do not.
n_needs=$(( n_flagged + n_skipped ))

DATE_ONLY="${RAN_AT%% *}"

emit_report() {
  printf '# Dream — %s\n\n' "$DATE_ONLY"

  if [ "$MODE" = "dry-run" ]; then
    printf '> **DRY RUN — nothing was pushed.** Every artifact below is real and was generated by the same code path that would have written it; only the push is withheld. Reviewing the generated diffs is the point of this stage.\n\n'
  fi

  # --- U1: header -------------------------------------------------------------
  printf '**Ran:** %s · **Mode:** %s · **Jobs:** %s · **Needs you: %s**\n\n' \
    "$RAN_AT" "$MODE" "$n_total" "$n_needs"

  if [ -n "$REPOS" ]; then
    printf '**State computed against:**\n\n'
    while IFS= read -r r; do
      [ -n "$r" ] || continue
      printf -- '- `%s` @ `%s`\n' "${r%%=*}" "${r#*=}"
    done <<EOF
$REPOS
EOF
    printf '\n'
  fi

  # A report that reaches here with no records is a BROKEN report, not a quiet
  # night — the pipeline produced nothing to say. Saying so loudly is the whole
  # value of writing unconditionally.
  if [ "$n_total" -eq 0 ]; then
    printf '## ⚠️ No job records\n\n'
    printf 'The report was written but no job reported a result. This is a malfunction, not a clean night — a clean night still emits one `clean` record per job. Check the run log.\n\n'
  fi

  # --- U2: what it did --------------------------------------------------------
  printf '## Did\n\n'
  if [ "$n_did" -eq 0 ]; then
    printf '_Nothing to do._\n\n'
  else
    awk -F'\t' '$2=="did"' "$RECORDS" | while IFS=$'\t' read -r job status summary detail link; do
      printf -- '- **%s** — %s' "$job" "$summary"
      [ -n "${link:-}" ] && printf ' · %s' "$link"
      printf '\n'
      [ -n "${detail:-}" ] && printf '  - %s\n' "$detail"
    done
    printf '\n'
  fi

  # --- U3: flagged, report-only -----------------------------------------------
  printf '## Flagged — no action taken\n\n'
  if [ "$n_flagged" -eq 0 ]; then
    printf '_Nothing flagged._\n\n'
  else
    awk -F'\t' '$2=="flagged"' "$RECORDS" | while IFS=$'\t' read -r job status summary detail link; do
      printf -- '- **%s** — %s\n' "$job" "$summary"
      [ -n "${detail:-}" ] && printf '  - %s\n' "$detail"
    done
    printf '\n'
  fi

  # --- skips get their own section: a silent skip is the failure mode ----------
  printf '## Skipped\n\n'
  if [ "$n_skipped" -eq 0 ]; then
    printf '_Nothing skipped._\n\n'
  else
    awk -F'\t' '$2=="skipped"' "$RECORDS" | while IFS=$'\t' read -r job status summary detail link; do
      printf -- '- **%s** — %s\n' "$job" "$summary"
      [ -n "${detail:-}" ] && printf '  - %s\n' "$detail"
    done
    printf '\n'
  fi

  # --- U4: the morning half ---------------------------------------------------
  printf '## Waiting on you\n\n'
  printf 'Run `/dream morning` locally. The cloud half cannot see `~/.claude` (memory, checkpoints, sessions) or `example-app/tmp/`, which is gitignored and therefore invisible to a clone (KD-10). Those are the morning half'"'"'s scope.\n\n'

  # --- U6: proof of liveness — every job, always ------------------------------
  printf '## Every job checked\n\n'
  printf '| Job | Result | Detail |\n|---|---|---|\n'
  if [ "$n_total" -eq 0 ]; then
    printf '| _(none reported)_ | ⚠️ malfunction | no records reached the report |\n'
  else
    awk -F'\t' 'NF && $0 ~ /[^[:space:]]/' "$RECORDS" | while IFS=$'\t' read -r job status summary detail link; do
      case "$status" in
        did)     icon="✅ acted" ;;
        clean)   icon="✅ nothing found" ;;
        flagged) icon="🚩 flagged" ;;
        skipped) icon="⏭️ skipped" ;;
        *)       icon="❓ $status" ;;
      esac
      # The Detail column renders $detail, falling back to $summary when a record
      # carries none. It previously printed $summary under a "Detail" header, which
      # made the table a duplicate of the sections above it rather than the extra
      # context the header promises.
      cell="${detail:-}"
      [ -n "$cell" ] || cell="$summary"
      # Pipes in caller text would split the cell and shift every column after it.
      s=$(printf '%s' "$cell" | sed 's/|/\\|/g')
      printf '| %s | %s | %s |\n' "$job" "$icon" "$s"
    done
  fi
  printf '\n'

  printf -- '---\n\n'
  printf '_Generated by `dream-report.sh`. A missing report is the alarm (KD-6) — if you did not get one for a date, the run did not happen._\n'
}

write_to() { # write_to <path>
  local dest="$1" dir
  dir=$(dirname "$dest")
  mkdir -p "$dir" || { echo "dream-report.sh: cannot create $dir" >&2; return 1; }
  emit_report > "$dest" || { echo "dream-report.sh: cannot write $dest" >&2; return 1; }
  printf 'report written: %s\n' "$dest"
}

write_to "$OUT" || exit 1
# The second location is a convenience copy. Failing the whole run because the
# convenience copy could not be written would trade the canonical report — the
# thing KD-6 depends on existing — for a secondary one.
if [ -n "$ALSO" ]; then
  write_to "$ALSO" || echo "dream-report.sh: WARNING — secondary copy failed, canonical report at $OUT is intact" >&2
fi
